sudo: true
language: node_js
noje_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run test-build
  - npm run build
branches:
  only:
    - master
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "financial-manager-v2"
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
